// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

/**
 * Protobuf type {@code cn.hua.netty.grpc_example.AnimalResponseList}
 */
public  final class AnimalResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.hua.netty.grpc_example.AnimalResponseList)
    AnimalResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalResponseList.newBuilder() to construct.
  private AnimalResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalResponseList() {
    animalResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              animalResponse_ = new java.util.ArrayList<cn.hua.netty.grpc_example.AnimalResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            animalResponse_.add(
                input.readMessage(cn.hua.netty.grpc_example.AnimalResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        animalResponse_ = java.util.Collections.unmodifiableList(animalResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.hua.netty.grpc_example.AnimalProto.internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.hua.netty.grpc_example.AnimalProto.internal_static_cn_hua_netty_grpc_example_AnimalResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.hua.netty.grpc_example.AnimalResponseList.class, cn.hua.netty.grpc_example.AnimalResponseList.Builder.class);
  }

  public static final int ANIMALRESPONSE_FIELD_NUMBER = 1;
  private java.util.List<cn.hua.netty.grpc_example.AnimalResponse> animalResponse_;
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  public java.util.List<cn.hua.netty.grpc_example.AnimalResponse> getAnimalResponseList() {
    return animalResponse_;
  }
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  public java.util.List<? extends cn.hua.netty.grpc_example.AnimalResponseOrBuilder> 
      getAnimalResponseOrBuilderList() {
    return animalResponse_;
  }
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  public int getAnimalResponseCount() {
    return animalResponse_.size();
  }
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  public cn.hua.netty.grpc_example.AnimalResponse getAnimalResponse(int index) {
    return animalResponse_.get(index);
  }
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  public cn.hua.netty.grpc_example.AnimalResponseOrBuilder getAnimalResponseOrBuilder(
      int index) {
    return animalResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < animalResponse_.size(); i++) {
      output.writeMessage(1, animalResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < animalResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, animalResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.hua.netty.grpc_example.AnimalResponseList)) {
      return super.equals(obj);
    }
    cn.hua.netty.grpc_example.AnimalResponseList other = (cn.hua.netty.grpc_example.AnimalResponseList) obj;

    boolean result = true;
    result = result && getAnimalResponseList()
        .equals(other.getAnimalResponseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnimalResponseCount() > 0) {
      hash = (37 * hash) + ANIMALRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.hua.netty.grpc_example.AnimalResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.hua.netty.grpc_example.AnimalResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.hua.netty.grpc_example.AnimalResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.hua.netty.grpc_example.AnimalResponseList)
      cn.hua.netty.grpc_example.AnimalResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.hua.netty.grpc_example.AnimalProto.internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.hua.netty.grpc_example.AnimalProto.internal_static_cn_hua_netty_grpc_example_AnimalResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.hua.netty.grpc_example.AnimalResponseList.class, cn.hua.netty.grpc_example.AnimalResponseList.Builder.class);
    }

    // Construct using cn.hua.netty.grpc_example.AnimalResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnimalResponseFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (animalResponseBuilder_ == null) {
        animalResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        animalResponseBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.hua.netty.grpc_example.AnimalProto.internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor;
    }

    public cn.hua.netty.grpc_example.AnimalResponseList getDefaultInstanceForType() {
      return cn.hua.netty.grpc_example.AnimalResponseList.getDefaultInstance();
    }

    public cn.hua.netty.grpc_example.AnimalResponseList build() {
      cn.hua.netty.grpc_example.AnimalResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.hua.netty.grpc_example.AnimalResponseList buildPartial() {
      cn.hua.netty.grpc_example.AnimalResponseList result = new cn.hua.netty.grpc_example.AnimalResponseList(this);
      int from_bitField0_ = bitField0_;
      if (animalResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          animalResponse_ = java.util.Collections.unmodifiableList(animalResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.animalResponse_ = animalResponse_;
      } else {
        result.animalResponse_ = animalResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.hua.netty.grpc_example.AnimalResponseList) {
        return mergeFrom((cn.hua.netty.grpc_example.AnimalResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.hua.netty.grpc_example.AnimalResponseList other) {
      if (other == cn.hua.netty.grpc_example.AnimalResponseList.getDefaultInstance()) return this;
      if (animalResponseBuilder_ == null) {
        if (!other.animalResponse_.isEmpty()) {
          if (animalResponse_.isEmpty()) {
            animalResponse_ = other.animalResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnimalResponseIsMutable();
            animalResponse_.addAll(other.animalResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.animalResponse_.isEmpty()) {
          if (animalResponseBuilder_.isEmpty()) {
            animalResponseBuilder_.dispose();
            animalResponseBuilder_ = null;
            animalResponse_ = other.animalResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            animalResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnimalResponseFieldBuilder() : null;
          } else {
            animalResponseBuilder_.addAllMessages(other.animalResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.hua.netty.grpc_example.AnimalResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.hua.netty.grpc_example.AnimalResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cn.hua.netty.grpc_example.AnimalResponse> animalResponse_ =
      java.util.Collections.emptyList();
    private void ensureAnimalResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        animalResponse_ = new java.util.ArrayList<cn.hua.netty.grpc_example.AnimalResponse>(animalResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.hua.netty.grpc_example.AnimalResponse, cn.hua.netty.grpc_example.AnimalResponse.Builder, cn.hua.netty.grpc_example.AnimalResponseOrBuilder> animalResponseBuilder_;

    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public java.util.List<cn.hua.netty.grpc_example.AnimalResponse> getAnimalResponseList() {
      if (animalResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(animalResponse_);
      } else {
        return animalResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public int getAnimalResponseCount() {
      if (animalResponseBuilder_ == null) {
        return animalResponse_.size();
      } else {
        return animalResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public cn.hua.netty.grpc_example.AnimalResponse getAnimalResponse(int index) {
      if (animalResponseBuilder_ == null) {
        return animalResponse_.get(index);
      } else {
        return animalResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder setAnimalResponse(
        int index, cn.hua.netty.grpc_example.AnimalResponse value) {
      if (animalResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalResponseIsMutable();
        animalResponse_.set(index, value);
        onChanged();
      } else {
        animalResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder setAnimalResponse(
        int index, cn.hua.netty.grpc_example.AnimalResponse.Builder builderForValue) {
      if (animalResponseBuilder_ == null) {
        ensureAnimalResponseIsMutable();
        animalResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        animalResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder addAnimalResponse(cn.hua.netty.grpc_example.AnimalResponse value) {
      if (animalResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalResponseIsMutable();
        animalResponse_.add(value);
        onChanged();
      } else {
        animalResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder addAnimalResponse(
        int index, cn.hua.netty.grpc_example.AnimalResponse value) {
      if (animalResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalResponseIsMutable();
        animalResponse_.add(index, value);
        onChanged();
      } else {
        animalResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder addAnimalResponse(
        cn.hua.netty.grpc_example.AnimalResponse.Builder builderForValue) {
      if (animalResponseBuilder_ == null) {
        ensureAnimalResponseIsMutable();
        animalResponse_.add(builderForValue.build());
        onChanged();
      } else {
        animalResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder addAnimalResponse(
        int index, cn.hua.netty.grpc_example.AnimalResponse.Builder builderForValue) {
      if (animalResponseBuilder_ == null) {
        ensureAnimalResponseIsMutable();
        animalResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        animalResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder addAllAnimalResponse(
        java.lang.Iterable<? extends cn.hua.netty.grpc_example.AnimalResponse> values) {
      if (animalResponseBuilder_ == null) {
        ensureAnimalResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, animalResponse_);
        onChanged();
      } else {
        animalResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder clearAnimalResponse() {
      if (animalResponseBuilder_ == null) {
        animalResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        animalResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public Builder removeAnimalResponse(int index) {
      if (animalResponseBuilder_ == null) {
        ensureAnimalResponseIsMutable();
        animalResponse_.remove(index);
        onChanged();
      } else {
        animalResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public cn.hua.netty.grpc_example.AnimalResponse.Builder getAnimalResponseBuilder(
        int index) {
      return getAnimalResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public cn.hua.netty.grpc_example.AnimalResponseOrBuilder getAnimalResponseOrBuilder(
        int index) {
      if (animalResponseBuilder_ == null) {
        return animalResponse_.get(index);  } else {
        return animalResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public java.util.List<? extends cn.hua.netty.grpc_example.AnimalResponseOrBuilder> 
         getAnimalResponseOrBuilderList() {
      if (animalResponseBuilder_ != null) {
        return animalResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(animalResponse_);
      }
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public cn.hua.netty.grpc_example.AnimalResponse.Builder addAnimalResponseBuilder() {
      return getAnimalResponseFieldBuilder().addBuilder(
          cn.hua.netty.grpc_example.AnimalResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public cn.hua.netty.grpc_example.AnimalResponse.Builder addAnimalResponseBuilder(
        int index) {
      return getAnimalResponseFieldBuilder().addBuilder(
          index, cn.hua.netty.grpc_example.AnimalResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
     */
    public java.util.List<cn.hua.netty.grpc_example.AnimalResponse.Builder> 
         getAnimalResponseBuilderList() {
      return getAnimalResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.hua.netty.grpc_example.AnimalResponse, cn.hua.netty.grpc_example.AnimalResponse.Builder, cn.hua.netty.grpc_example.AnimalResponseOrBuilder> 
        getAnimalResponseFieldBuilder() {
      if (animalResponseBuilder_ == null) {
        animalResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.hua.netty.grpc_example.AnimalResponse, cn.hua.netty.grpc_example.AnimalResponse.Builder, cn.hua.netty.grpc_example.AnimalResponseOrBuilder>(
                animalResponse_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        animalResponse_ = null;
      }
      return animalResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.hua.netty.grpc_example.AnimalResponseList)
  }

  // @@protoc_insertion_point(class_scope:cn.hua.netty.grpc_example.AnimalResponseList)
  private static final cn.hua.netty.grpc_example.AnimalResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.hua.netty.grpc_example.AnimalResponseList();
  }

  public static cn.hua.netty.grpc_example.AnimalResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalResponseList>
      PARSER = new com.google.protobuf.AbstractParser<AnimalResponseList>() {
    public AnimalResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalResponseList> getParserForType() {
    return PARSER;
  }

  public cn.hua.netty.grpc_example.AnimalResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

