// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

public interface AnimalResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.hua.netty.grpc_example.AnimalResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  java.util.List<cn.hua.netty.grpc_example.AnimalResponse> 
      getAnimalResponseList();
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  cn.hua.netty.grpc_example.AnimalResponse getAnimalResponse(int index);
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  int getAnimalResponseCount();
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  java.util.List<? extends cn.hua.netty.grpc_example.AnimalResponseOrBuilder> 
      getAnimalResponseOrBuilderList();
  /**
   * <code>repeated .cn.hua.netty.grpc_example.AnimalResponse animalResponse = 1;</code>
   */
  cn.hua.netty.grpc_example.AnimalResponseOrBuilder getAnimalResponseOrBuilder(
      int index);
}
