// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

public final class AnimalProto {
  private AnimalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_AnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_AnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_AnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_AnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_AnimalResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hua_netty_grpc_example_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hua_netty_grpc_example_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014animal.proto\022\031cn.hua.netty.grpc_exampl" +
      "e\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRe" +
      "sponse\022\020\n\010realname\030\002 \001(\t\"\034\n\rAnimalReques" +
      "t\022\013\n\003age\030\001 \001(\005\"9\n\016AnimalResponse\022\014\n\004name" +
      "\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"W\n\022Ani" +
      "malResponseList\022A\n\016animalResponse\030\001 \003(\0132" +
      ").cn.hua.netty.grpc_example.AnimalRespon" +
      "se\"%\n\rStreamRequest\022\024\n\014request_info\030\001 \001(" +
      "\t\"\'\n\016StreamResponse\022\025\n\rresponse_info\030\001 \001" +
      "(\t2\304\003\n\rAnimalService\022f\n\025getRealNameByUse" +
      "rName\022$.cn.hua.netty.grpc_example.MyRequ" +
      "est\032%.cn.hua.netty.grpc_example.MyRespon" +
      "se\"\000\022j\n\017getAnimalsByAge\022(.cn.hua.netty.g" +
      "rpc_example.AnimalRequest\032).cn.hua.netty" +
      ".grpc_example.AnimalResponse\"\0000\001\022z\n\033getA" +
      "nimalResponseListByAges\022(.cn.hua.netty.g" +
      "rpc_example.AnimalRequest\032-.cn.hua.netty" +
      ".grpc_example.AnimalResponseList\"\000(\001\022c\n\006" +
      "biTalk\022(.cn.hua.netty.grpc_example.Strea" +
      "mRequest\032).cn.hua.netty.grpc_example.Str" +
      "eamResponse\"\000(\0010\001B*\n\031cn.hua.netty.grpc_e" +
      "xampleB\013AnimalProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_hua_netty_grpc_example_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_hua_netty_grpc_example_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_cn_hua_netty_grpc_example_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_hua_netty_grpc_example_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_cn_hua_netty_grpc_example_AnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_hua_netty_grpc_example_AnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_AnimalRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_cn_hua_netty_grpc_example_AnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cn_hua_netty_grpc_example_AnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_AnimalResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cn_hua_netty_grpc_example_AnimalResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_AnimalResponseList_descriptor,
        new java.lang.String[] { "AnimalResponse", });
    internal_static_cn_hua_netty_grpc_example_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cn_hua_netty_grpc_example_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_cn_hua_netty_grpc_example_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cn_hua_netty_grpc_example_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hua_netty_grpc_example_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
