// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

public interface AnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.hua.netty.grpc_example.AnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
