// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.hua.netty.grpc_example.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
