// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package cn.hua.netty.grpc_example;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.hua.netty.grpc_example.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
